In [1]:
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
from sklearn import tree

In [5]:
from IPython.display import Image

In [6]:
import pandas as pd

In [7]:
import numpy as np

In [9]:
import pydotplus     # Anaconda Prompt에서 pip install pydotplus 라고 치면 pydotplus가 설치된다.

In [10]:
import os

In [17]:
tennis_data = pd.read_csv('playtennis.csv')
tennis_data

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [18]:
tennis_data.outlook = tennis_data.outlook.replace('sunny',0)
tennis_data.outlook = tennis_data.outlook.replace('overcast', 1)
tennis_data.outlook = tennis_data.outlook.replace('rainy',2)

tennis_data.temp = tennis_data.temp.replace('hot',3)
tennis_data.temp = tennis_data.temp.replace('mild',4)
tennis_data.temp = tennis_data.temp.replace('cool',5)

tennis_data.humidity = tennis_data.humidity.replace('high',6)
tennis_data.humidity = tennis_data.humidity.replace('normal',7)

tennis_data.windy = tennis_data.windy.replace(False,8)
tennis_data.windy = tennis_data.windy.replace(True,9)

tennis_data.play = tennis_data.play.replace('no',10)
tennis_data.play = tennis_data.play.replace('yes',11)

tennis_data

outlook  temp  humidity  windy  play
0         0     3         6      8    10
1         0     3         6      9    10
2         1     3         6      8    11
3         2     4         6      8    11
4         2     5         7      8    11
5         2     5         7      9    10
6         1     5         7      9    11
7         0     4         6      8    10
8         0     5         7      8    11
9         2     4         7      8    11
10        0     4         7      9    11
11        1     4         6      9    11
12        1     3         7      8    11
13        2     4         6      9    10

In [19]:
X = np.array(pd.DataFrame(tennis_data, columns=['outlook','temp', 'humidity', 'windy']))

In [20]:
y = np.array(pd.DataFrame(tennis_data, columns=['play']))

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [22]:
X_train

array([[0, 4, 7, 9],
       [2, 4, 7, 8],
       [0, 3, 6, 9],
       [1, 4, 6, 9],
       [0, 5, 7, 8],
       [2, 5, 7, 9],
       [1, 3, 6, 8],
       [0, 4, 6, 8],
       [0, 3, 6, 8],
       [2, 5, 7, 8]], dtype=int64)

In [23]:
X_test

array([[1, 5, 7, 9],
       [2, 4, 6, 9],
       [2, 4, 6, 8],
       [1, 3, 7, 8]], dtype=int64)

In [24]:
y_train

array([[11],
       [11],
       [10],
       [11],
       [11],
       [10],
       [11],
       [10],
       [10],
       [11]], dtype=int64)

In [25]:
y_test

array([[11],
       [10],
       [11],
       [11]], dtype=int64)

In [26]:
dt_clf = DecisionTreeClassifier()

In [27]:
dt_clf = dt_clf.fit(X_train, y_train)

In [28]:
dt_prediction = dt_clf.predict(X_test)